### PR TITLE
Fixes lack of dashed lines in supervisor edges in direct graph.

### PR DESCRIPTION
**Pull request by azurebrd**
Finds error for lack of scaling in Direct graph nodes, keeps lack of
scaling for Full graph nodes.

### CODE REVIEW

**Comment by azurebrd** [comment]
Line 205 doesn't work, but is left as a placeholder with a potential fix.

Line 206 doesn't work because :radius already exists, so (conj) doesn't replace the old value with the new one.  I think (update-in) should be able to replace the value, but I can't figure out the syntax for replacing the existing value with the radius.  

Added some code to only call scale-nodes-map when it's "Direct", but still needs to add a restriction to not call it when "is-primary"

**Comment by adamjohnwright** [comment]
Looks like good progress. Could you try conj with the elements in the other order? I think the first gets replaced with the second one.

**Comment by azurebrd** [comment]
Ah, thanks, that works.  I see other problems with it now, the Full view doesn't get updated.  I'll work on that.

**Review by adamjohnwright — APPROVED** [review]

**Comment by azurebrd** [comment]
I've updated the code to fix the scaling of the primary node in direct view, and the error with loading the full view.  Still needs testing of other objects, will keep you updated.

**Comment by azurebrd** [comment]
Updated Full view to keep scaling.  Finding an error with WBPerson77, will debug.

**Comment by azurebrd** [comment]
Error also exists in staging version. Browser console says : 

SyntaxError: missing } after property list[Learn More]
jquery.js:9597:4
note: { opened at line 3, column 301450
jquery.js:9597:4

Works on live site, but can't tell how the json output is different.

**Comment by azurebrd** [comment]
Found and fixed some more errors:
Persons with standard name blank now have a default.
Supervise graph direction with no edges now get the nil role filtered out.
Persons with apostrophe in their names have them removed, but this is not ideal.  @a8wright do you how we could make the syntax to end up with \\' in the output ?  Line 243 has an example of what it should look like, and that should be fixed in line 62.  I tried \' \\' (results in just ') \\\\' (results in \\\\') other amounts of \ give errors and don't generate data.

**Pull request merged**
