### PR TITLE
Was splitting 'publication date' string, and data is empty for papers…

### PR DESCRIPTION
**Pull request by azurebrd**
… like

WBPaper00000974, causing an error.

### CODE REVIEW

**Comment by azurebrd** [comment]
http://www.wormbase.org/resources/person/WBPerson320#053--10
Has some papers with unknown year showing as if they were grouped with the oldest year, since there's a blank as the key for the year, it doesn't make a year header in the display.  compare with 
http://juancarlos.wormbase.org/resources/person/WBPerson320#053--10

**Comment by azurebrd** [comment]
Emailed Kimberly (Paper curator) for feedback.

**Comment by vanaukenk** [comment]
Thanks @azurebrd .
For now, let's give these papers the heading 'Year Not Available'.
In the meantime, I think I just need to get the list of paper objects with no year and see how many we can populate.  For WBPaper00000974, for example, I was able to add the correct year.

**Comment by azurebrd** [comment]
Thanks @vanaukenk 

Updated and will make a pull request.

If you want to find the papers in postgres, this query should give you them, but it's a slow query to run.
SELECT * FROM pap_status WHERE pap_status = 'valid' AND joinkey NOT IN (SELECT joinkey FROM pap_year);

**Pull request merged**
